///////////////////////////////////////////////////////////
//  Contract.cs
//  Implementation of the Class Contract
//  Generated by Enterprise Architect
//  Created on:      07-Ò»ÔÂ-2009 23:56:34
//  Original author: anaki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using TVMS.Model;
using TVMS.IDAL;


namespace TVMS.BLL {
	public class Contract {

		public IList<ContractInfo> GetContracts(){

			return null;
		}

		/// 
		/// <param name="contractId"></param>
		public ContractInfo GetContract(int contractId){

			return null;
		}

		/// 
		/// <param name="contract"></param>
		public void Insert(ContractInfo contract){

		}

		/// 
		/// <param name="contractId"></param>
		public void Delete(int contractId){

		}

		/// 
		/// <param name="contract"></param>
		public void Save(ContractInfo contract){

		}

	}//end Contract

}//end namespace BLL//end namespace BLL