///////////////////////////////////////////////////////////
//  Customer.cs
//  Implementation of the Class Customer
//  Generated by Enterprise Architect
//  Created on:      07-Ò»ÔÂ-2009 23:56:35
//  Original author: anaki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using TVMS.Model;
using TVMS.IDAL;


namespace TVMS.BLL {
	public class Customer {

        private static readonly ICustomer dal = TVMS.DALFactory.DataAccess.CreateCustomer();

        public IList<CustomerInfo> GetCustomers(){

			return dal.GetCustomers();
		}

		/// 
		/// <param name="customerId"></param>
		public CustomerInfo GetCustomer(int customerId){

			return null;
		}

		/// 
		/// <param name="customer"></param>
		public void Insert(CustomerInfo customer){

		}

		/// 
		/// <param name="customerId"></param>
		public void Delete(int customerId){

		}

		/// 
		/// <param name="customer"></param>
		public void Update(CustomerInfo customer){

		}

	}//end Customer

}//end namespace BLL//end namespace BLL