///////////////////////////////////////////////////////////
//  Tenement.cs
//  Implementation of the Class Tenement
//  Generated by Enterprise Architect
//  Created on:      07-Ò»ÔÂ-2009 23:56:35
//  Original author: anaki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using TVMS.Model;
using TVMS.IDAL;


namespace TVMS.BLL {
	public class Tenement {

        private static readonly ITenement dal = TVMS.DALFactory.DataAccess.CreateTenement();

        public IList<TenementInfo> GetTenements()
        {
			return dal.GetTenements();
		}

		/// 
		/// <param name="tenementId"></param>
		public TenementInfo GetTenement(int tenementId){

			return dal.GetTenement(tenementId);
		}

		/// 
		/// <param name="tenement"></param>
		public void Insert(TenementInfo tenement){
            dal.Insert(tenement);
		}

		/// 
		/// <param name="tenementId"></param>
		public void Delete(int tenementId){
            dal.Delete(tenementId);
		}

		/// 
		/// <param name="tenement"></param>
		public void Update(TenementInfo tenement){
            dal.Update(tenement);
		}

	}//end Tenement

}//end namespace BLL//end namespace BLL