///////////////////////////////////////////////////////////
//  Tenement.cs
//  Implementation of the Class Tenement
//  Generated by Enterprise Architect
//  Created on:      07-Ò»ÔÂ-2009 23:56:35
//  Original author: anaki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using TVMS.Model;
using TVMS.IDAL;


namespace TVMS.BLL {
	public class Tenement {

		public IList<TenementInfo> GetTenements(){

			return null;
		}

		/// 
		/// <param name="tenementId"></param>
		public TenementInfo GetTenement(int tenementId){

			return null;
		}

		/// 
		/// <param name="tenement"></param>
		public void Insert(TenementInfo tenement){

		}

		/// 
		/// <param name="tenementId"></param>
		public void Delete(int tenementId){

		}

		/// 
		/// <param name="tenement"></param>
		public void Save(TenementInfo tenement){

		}

	}//end Tenement

}

namespace BLL {
	public class Tenement {

		public Tenement(){

		}

		~Tenement(){

		}

		/// 
		/// <param name="tenementId"></param>
		public void Delete(int tenementId){

		}

		/// 
		/// <param name="tenementId"></param>
		public TenementInfo GetTenement(int tenementId){

			return null;
		}

		public IList<TenementInfo> GetTenements(){

			return null;
		}

		/// 
		/// <param name="tenement"></param>
		public void Insert(TenementInfo tenement){

		}

		/// 
		/// <param name="tenement"></param>
		public void Save(TenementInfo tenement){

		}

	}//end Tenement

}//end namespace BLL//end namespace BLL