///////////////////////////////////////////////////////////
//  DataAccess.cs
//  Implementation of the Class DataAccess
//  Generated by Enterprise Architect
//  Created on:      08-Ò»ÔÂ-2009 00:16:48
//  Original author: anaki
///////////////////////////////////////////////////////////

using System.Reflection;
using System.Configuration;


namespace TVMS.DALFactory {
	public sealed class DataAccess {

        private static readonly string dalAssembly = TVMS.Properties.Settings.Default.CommonDAL;
        private static readonly string dalNamespace = "TVMS.OleDbDAL";

        private DataAccess(){

		}

        public static TVMS.IDAL.IContract CreateContract() {
            string className = dalNamespace + ".Contract";
            return (TVMS.IDAL.IContract)Assembly.Load(dalAssembly).CreateInstance(className);
        }

        public static TVMS.IDAL.ICustomer CreateCustomer() {
            string className = dalNamespace + ".Customer";
            return (TVMS.IDAL.ICustomer)Assembly.Load(dalAssembly).CreateInstance(className);
        }

        public static TVMS.IDAL.IQuarters CreateQuarters() {
            string className = dalNamespace + ".Quarters";
            return (TVMS.IDAL.IQuarters)Assembly.Load(dalAssembly).CreateInstance(className);
        }

        public static TVMS.IDAL.ISale CreateSale() {
            string className = dalNamespace + ".Sale";
            return (TVMS.IDAL.ISale)Assembly.Load(dalAssembly).CreateInstance(className);
        }

        public static TVMS.IDAL.ITenement CreateTenement() {
            string className = dalNamespace + ".Tenement";
            return (TVMS.IDAL.ITenement)Assembly.Load(dalAssembly).CreateInstance(className);
        }

    }//end DataAccess

}//end namespace DALFactory