///////////////////////////////////////////////////////////
//  DataAccess.cs
//  Implementation of the Class DataAccess
//  Generated by Enterprise Architect
//  Created on:      08-Ò»ÔÂ-2009 00:16:48
//  Original author: anaki
///////////////////////////////////////////////////////////

using System.Reflection;
using System.Configuration;


namespace TVMS.DALFactory {
	public sealed class DataAccess {

        private static readonly string path = TVMS.Properties.Settings.Default.CommonDAL;

        private DataAccess(){

		}

        public static TVMS.IDAL.IContract CreateContract() {
            string className = path + ".Contract";
            return (TVMS.IDAL.IContract)Assembly.Load(path).CreateInstance(className);
        }

        public static TVMS.IDAL.ICustomer CreateCustomer() {
            string className = path + ".Customer";
            return (TVMS.IDAL.ICustomer)Assembly.Load(path).CreateInstance(className);
        }

        public static TVMS.IDAL.IQuarters CreateQuarters() {
            string className = path + ".Quarters";
            return (TVMS.IDAL.IQuarters)Assembly.Load(path).CreateInstance(className);
        }

        public static TVMS.IDAL.ISale CreateSale() {
            string className = path + ".Sale";
            return (TVMS.IDAL.ISale)Assembly.Load(path).CreateInstance(className);
        }

        public static TVMS.IDAL.ITenement CreateTenement() {
            string className = path + ".Tenement";
            return (TVMS.IDAL.ITenement)Assembly.Load(path).CreateInstance(className);
        }

    }//end DataAccess

}//end namespace DALFactory