///////////////////////////////////////////////////////////
//  Quarters.cs
//  Implementation of the Class Quarters
//  Generated by Enterprise Architect
//  Created on:      07-Ò»ÔÂ-2009 23:56:35
//  Original author: anaki
///////////////////////////////////////////////////////////

using System;
using System.Data;
using System.Data.OleDb;
using System.Collections.Generic;
using TVMS.Model;
using TVMS.IDAL;
using TVMS.DBUtility;


namespace TVMS.OleDbDAL {
	public class Quarters : IQuarters {

		/// 
		/// <param name="tenementId"></param>
		public IList<QuartersInfo> GetQuartersByTenement(int tenementId){

			return null;
		}

		/// 
		/// <param name="quartersId"></param>
		public QuartersInfo GetQuarters(int quartersId){

			return null;
		}

		/// 
		/// <param name="quarters"></param>
		public void Insert(QuartersInfo quarters){

		}

		/// 
		/// <param name="quartersId"></param>
		public void Delete(int quartersId){

		}

		/// 
		/// <param name="quarters"></param>
		public void Update(QuartersInfo quarters){

		}

		/// 
		/// <param name="keywords"></param>
		public IList<QuartersInfo> GetQuartersBySearch(string[] keywords){

			return null;
		}

	}//end Quarters

}//end namespace OleDbDAL