///////////////////////////////////////////////////////////
//  IContract.cs
//  Implementation of the Interface IContract
//  Generated by Enterprise Architect
//  Created on:      07-Ò»ÔÂ-2009 23:49:59
//  Original author: anaki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;


using TVMS.Model;
namespace TVMS.IDAL {
	public interface IContract {

		/// 
		/// <param name="contractId"></param>
		void Delete(int contractId);

		/// 
		/// <param name="contractId"></param>
		ContractInfo GetContract(int contractId);

		IList<ContractInfo> GetContracts();

		/// 
		/// <param name="contract"></param>
		void Insert(ContractInfo contract);

		/// 
		/// <param name="contract"></param>
		void Update(ContractInfo contract);
	}//end IContract

}//end namespace IDAL