///////////////////////////////////////////////////////////
//  IQuarters.cs
//  Implementation of the Interface IQuarters
//  Generated by Enterprise Architect
//  Created on:      07-Ò»ÔÂ-2009 23:49:59
//  Original author: anaki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;


using TVMS.Model;
namespace TVMS.IDAL {
	public interface IQuarters {

		/// 
		/// <param name="quartersId"></param>
		void Delete(int quartersId);

		IList<QuartersInfo> GetQuarters();

        /// 
        /// <param name="quartersId"></param>
        QuartersInfo GetQuarters(int quartersId);

        /// 
		/// <param name="keywords"></param>
		IList<QuartersInfo> GetQuartersBySearch(string[] keywords);

		/// 
		/// <param name="tenementId"></param>
		IList<QuartersInfo> GetQuartersByTenement(int tenementId);

		/// 
		/// <param name="quarters"></param>
		void Insert(QuartersInfo quarters);

		/// 
		/// <param name="quarters"></param>
		void Update(QuartersInfo quarters);
	}//end IQuarters

}//end namespace IDAL