///////////////////////////////////////////////////////////
//  ITenement.cs
//  Implementation of the Interface ITenement
//  Generated by Enterprise Architect
//  Created on:      07-Ò»ÔÂ-2009 23:49:59
//  Original author: anaki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;


using TVMS.Model;
namespace TVMS.IDAL {
	public interface ITenement {

		/// 
		/// <param name="tenementId"></param>
		void Delete(int tenementId);

		/// 
		/// <param name="tenementId"></param>
		TenementInfo GetTenement(int tenementId);

		IList<TenementInfo> GetTenements();

		/// 
		/// <param name="tenement"></param>
		void Insert(TenementInfo tenement);

		/// 
		/// <param name="tenement"></param>
		void Update(TenementInfo tenement);
	}//end ITenement

}//end namespace IDAL