///////////////////////////////////////////////////////////
//  CustomerInfo.cs
//  Implementation of the Class CustomerInfo
//  Generated by Enterprise Architect
//  Created on:      07-一月-2009 20:08:54
//  Original author: anaki
///////////////////////////////////////////////////////////

using System;


namespace TVMS.Model {
	public class CustomerInfo {

		/// <summary>
		/// 通讯地址
		/// </summary>
		private string address;
		/// <summary>
		/// 客户编号
		/// </summary>
		private int customerId;
		/// <summary>
		/// 客户姓名
		/// </summary>
		private string name;
		/// <summary>
		/// 联系电话
		/// </summary>
		private string tel;

		public CustomerInfo(){

		}

        /// 
        /// <param name="customerId"></param>
        /// <param name="name"></param>
        /// <param name="address"></param>
        /// <param name="tel"></param>
        public CustomerInfo(int customerId, string name, string address, string tel)
        {
            this.customerId = customerId;
            this.name = name;
            this.address = address;
            this.tel = tel;
        }

        /// <summary>
		/// 通讯地址
		/// </summary>
		public string Address{
			get{
				return address;
			}
			set{
				address = value;
			}
		}

		/// <summary>
		/// 客户编号
		/// </summary>
		public int CustomerId{
			get{
				return customerId;
			}
			set{
				customerId = value;
			}
		}

		/// <summary>
		/// 客户姓名
		/// </summary>
		public string Name{
			get{
				return name;
			}
			set{
				name = value;
			}
		}

		/// <summary>
		/// 联系电话
		/// </summary>
		public string Tel{
			get{
				return tel;
			}
			set{
				tel = value;
			}
		}

	}//end CustomerInfo

}//end namespace Model