///////////////////////////////////////////////////////////
//  QuartersInfo.cs
//  Implementation of the Class QuartersInfo
//  Generated by Enterprise Architect
//  Created on:      07-一月-2009 20:08:54
//  Original author: anaki
///////////////////////////////////////////////////////////

using System;


namespace TVMS.Model {
	public class QuartersInfo {

		/// <summary>
		/// 代码
		/// </summary>
		private string code;
		/// <summary>
		/// 门牌号
		/// </summary>
		private string doorplate;
		/// <summary>
		/// 市场价格
		/// </summary>
		private decimal marketPrice;
		/// <summary>
		/// 房型
		/// </summary>
		private int model;
		/// <summary>
		/// 权属性质
		/// </summary>
		private int property;
		/// <summary>
		/// 套数
		/// </summary>
		private int quantity;
		/// <summary>
		/// 住宅编号
		/// </summary>
		private int quartersId;
		/// <summary>
		/// 项目编号
		/// </summary>
		private int tenementId;
		/// <summary>
		/// 建筑面积
		/// </summary>
		private float builtUpArea;

		public QuartersInfo(){

		}

        /// 
		/// <param name="quartersId"></param>
		/// <param name="model"></param>
		/// <param name="builtUpArea"></param>
		/// <param name="property"></param>
		/// <param name="doorplate"></param>
		/// <param name="marketPrice"></param>
		/// <param name="tenementId"></param>
		/// <param name="code"></param>
		/// <param name="quantity"></param>
        public QuartersInfo(int quartersId, int model, float builtUpArea, int property, string doorplate, decimal marketPrice, int tenementId, string code, int quantity)
        {

        }

		/// <summary>
		/// 项目编号
		/// </summary>
		public int TenementId{
			get{
				return tenementId;
			}
			set{
				tenementId = value;
			}
		}

		/// <summary>
		/// 代码
		/// </summary>
		public string Code{
			get{
				return code;
			}
			set{
				code = value;
			}
		}

		/// <summary>
		/// 门牌号
		/// </summary>
		public string Doorplate{
			get{
				return doorplate;
			}
			set{
				doorplate = value;
			}
		}

		/// <summary>
		/// 市场价格
		/// </summary>
		public decimal MarketPrice{
			get{
				return marketPrice;
			}
			set{
				marketPrice = value;
			}
		}

		/// <summary>
		/// 房型
		/// </summary>
		public int Model{
			get{
				return model;
			}
			set{
				model = value;
			}
		}

		/// <summary>
		/// 权属性质
		/// </summary>
		public int Property{
			get{
				return property;
			}
			set{
				property = value;
			}
		}

		/// <summary>
		/// 套数
		/// </summary>
		public int Quantity{
			get{
				return quantity;
			}
			set{
				quantity = value;
			}
		}

		/// <summary>
		/// 住宅编号
		/// </summary>
		public int QuartersId{
			get{
				return quartersId;
			}
			set{
				quartersId = value;
			}
		}

		/// <summary>
		/// 建筑面积
		/// </summary>
		public float BuiltUpArea{
			get{
				return builtUpArea;
			}
			set{
				builtUpArea = value;
			}
		}

	}//end QuartersInfo

}//end namespace Model